# Generated by Django 5.1 on 2024-08-29 05:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('emp_no', models.IntegerField()),
                ('designation', models.CharField(max_length=64)),
                ('section', models.CharField(max_length=64)),
                ('phone', models.BigIntegerField()),
                ('remark', models.CharField(blank=True, max_length=150)),
                ('balance', models.IntegerField(default=0)),
                ('trash', models.BooleanField(default=False)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
